# Generated by Django 4.1.4 on 2024-09-03 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='likes',
            new_name='link',
        ),
    ]
