# Generated by Django 4.1.4 on 2024-09-09 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0002_rename_user_thread_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='message',
            new_name='messages',
        ),
    ]
